version: '3'

services:
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
      - 7199:7199
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  dependency-tracker:
    image: owasp/dependency-track
    ports:
      - 8080:8080